title: Watermelons
description: Picking sesame seeds and encountering watermelons.
lang: zh-CN
theme: just-the-docs

url: https://sesame-small.github.io

aux_links:
  Watermelons: https://github.com/sesame-small/watermelons

aux_links_new_tab: true

search_enabled: true

# background color
# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: dark

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

permalink: /:title/