title: Watermelons
description: Picking sesame seeds and encountering watermelons.
lang: zh-CN
theme: just-the-docs

url: https://sesame-small.github.io

aux_links:
  Watermelons: https://github.com/sesame-small/watermelons

aux_links_new_tab: true

search_enabled: true