title: Watermelons
description: Picking sesame seeds and encountering watermelons.
theme: just-the-docs

url: https://sesame-small.github.io

aux_links:
  Watermelons: https://github.com/sesame-small/watermelons
